local Fusion = require(script.Parent.Parent.Parent.Parent["elttob_fusion@0.3.0"]["fusion"])
type Fusion = typeof(Fusion)

export type Animatable = Fusion.Animatable
export type UsedAs<T> = Fusion.UsedAs<T>
export type Child = Fusion.Child
export type Computed<T> = Fusion.Computed<T>
export type Contextual<T> = Fusion.Contextual<T>
export type GraphObject = Fusion.GraphObject
export type For<KO, VO> = Fusion.For<KO, VO>
export type Observer = Fusion.Observer
export type PropertyTable = Fusion.PropertyTable
export type Scope<Constructors = Fusion> = Fusion.Scope<Constructors>
export type ScopedObject = Fusion.ScopedObject
export type SpecialKey = Fusion.SpecialKey
export type Spring<T> = Fusion.Spring<T>
export type StateObject<T> = Fusion.StateObject<T>
export type Task = Fusion.Task
export type Tween<T> = Fusion.Tween<T>
export type Use = Fusion.Use
export type Value<T, S = T> = Fusion.Value<T, S>
export type Version = Fusion.Version

return Fusion